if(UNIX)
  if(APPLE)
    file(GLOB installedLibs $ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/*.dylib)
    execute_process(COMMAND strip -x ${installedLibs})
  else()
    file(GLOB installedLibs $ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/*.so)
    execute_process(COMMAND strip ${installedLibs})
  endif()
endif()  