if(UNIX)
  if(APPLE)
    execute_process(COMMAND strip -x $ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libtypedobject.dylib)
  else()
    execute_process(COMMAND strip    $ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/libtypedobject.so)
  endif()
endif()